# Generated by Django 3.1.5 on 2021-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailId', models.CharField(max_length=50)),
                ('rollNo', models.IntegerField()),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
