# Generated by Django 3.1.5 on 2021-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Gujrati', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
