# Generated by Django 3.1.7 on 2021-03-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0003_auto_20210315_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
