# Generated by Django 3.1.5 on 2021-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
