# Generated by Django 3.1.7 on 2021-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0004_auto_20210326_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
