# Generated by Django 3.1.5 on 2021-03-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0004_auto_20210313_1432'),
        ('homemodule', '0004_auto_20210309_1942'),
    ]

    operations = [
    ]
