# Generated by Django 3.1.5 on 2021-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodule', '0005_merge_20210314_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
